#!/usr/bin/env bash
set -euo pipefail

# HexOS Phase 2 — DNS Control
# Forces client DNS through platform resolver, blocks direct DNS to external servers.
# Prevents DNS-based data exfiltration.
#
# This is integrated into the main egress rules generated by egress-apply.sh.
# This script provides standalone DNS control setup/verification.
#
# Usage: dns-control.sh <action> <client>
# Actions:
#   verify  — Check if DNS control is active
#   show    — Show DNS configuration
#   test    — Test DNS resolution from client context

export PATH="/usr/sbin:/sbin:${PATH}"

usage() {
    echo "Usage: dns-control.sh <action> <client>"
    echo ""
    echo "Actions:"
    echo "  verify  Check if DNS control rules are active"
    echo "  show    Show client DNS configuration"
    echo "  test    Test DNS resolution from client context"
    exit 1
}

[[ $# -lt 2 ]] && usage

ACTION="$1"
CLIENT="$2"

if [[ ! "$CLIENT" =~ ^[a-z][a-z0-9-]{1,30}[a-z0-9]$ ]]; then
    echo "Error: Invalid client name '${CLIENT}'"
    exit 1
fi

CLIENT_HOME="/hexos/${CLIENT}"
CONFIG_FILE="${CLIENT_HOME}/config/egress.yaml"
TABLE_NAME="hexos_${CLIENT//-/_}"
CLIENT_USER="hexos-${CLIENT}"

case "$ACTION" in
    verify)
        echo "Verifying DNS control for client: ${CLIENT}"
        echo ""

        # Check that egress rules exist
        if ! nft list table inet "${TABLE_NAME}" &>/dev/null; then
            echo "✗ No egress rules found — DNS is NOT controlled"
            echo "  Run: hexos egress apply ${CLIENT}"
            exit 1
        fi

        # Check for DNS rules in the chain
        rules=$(nft list table inet "${TABLE_NAME}" 2>/dev/null)

        # DNS to resolver only
        if echo "$rules" | grep -q "udp dport 53.*accept"; then
            resolver_ip=$(echo "$rules" | grep "udp dport 53" | grep -oP 'ip daddr \K[0-9.]+' | head -1)
            echo "✓ DNS to platform resolver: ${resolver_ip}"
        else
            echo "✗ No DNS allow rule found"
        fi

        # DNS is blocked by the default-deny (drop all at end of chain)
        if echo "$rules" | grep -q "counter drop"; then
            echo "✓ All other DNS queries blocked (by default-deny)"
        else
            echo "✗ Default-deny rule not found"
        fi

        # Check known DoH providers are not in allowlist
        echo ""
        echo "DNS-over-HTTPS bypass check:"
        known_doh=("1.1.1.1" "8.8.8.8" "8.8.4.4" "9.9.9.9" "208.67.222.222")
        for doh_ip in "${known_doh[@]}"; do
            if echo "$rules" | grep -q "$doh_ip"; then
                echo "  ⚠ DoH provider ${doh_ip} is in allowlist (potential DNS bypass)"
            else
                echo "  ✓ DoH provider ${doh_ip} is blocked"
            fi
        done

        echo ""
        echo "DNS control verification complete."
        ;;

    show)
        echo "DNS configuration for client: ${CLIENT}"
        echo ""

        if [[ -f "$CONFIG_FILE" ]]; then
            resolver=$(yq -r '.egress.dns.resolver // "127.0.0.53"' "$CONFIG_FILE" 2>/dev/null)
            allow_custom=$(yq -r '.egress.dns.allow_custom // false' "$CONFIG_FILE" 2>/dev/null)
            echo "  Resolver: ${resolver}"
            echo "  Allow custom DNS: ${allow_custom}"
        else
            echo "  No egress config — using default (127.0.0.53)"
        fi

        # Show resolv.conf for the client
        echo ""
        echo "  Client resolv.conf:"
        if [[ -f "${CLIENT_HOME}/.resolv.conf" ]]; then
            cat "${CLIENT_HOME}/.resolv.conf" | sed 's/^/    /'
        else
            echo "    (using system default)"
        fi
        ;;

    test)
        echo "Testing DNS resolution for client: ${CLIENT}"
        echo ""

        if ! id "$CLIENT_USER" &>/dev/null; then
            echo "⚠ User ${CLIENT_USER} does not exist — testing from current user"
            echo ""
        fi

        test_domains=("api.anthropic.com" "api.telegram.org" "evil-exfil.example.com" "google.com")
        for domain in "${test_domains[@]}"; do
            echo -n "  ${domain}: "
            if id "$CLIENT_USER" &>/dev/null; then
                result=$(sudo -u "$CLIENT_USER" dig +short +timeout=3 A "$domain" 2>/dev/null | head -1 || echo "FAILED")
            else
                result=$(dig +short +timeout=3 A "$domain" 2>/dev/null | head -1 || echo "FAILED")
            fi
            if [[ -n "$result" && "$result" != "FAILED" ]]; then
                echo "${result}"
            else
                echo "FAILED (blocked or timeout)"
            fi
        done
        ;;

    *)
        echo "Unknown action: ${ACTION}"
        usage
        ;;
esac
